services:
  db:
    image: mariadb:11
    container_name: mariadb-threedviewer
    command: ["--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW"]
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: nextcloud
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: nextcloud
    volumes:
      - db-data:/var/lib/mysql

  nextcloud:
    image: nextcloud:30-apache
    container_name: nextcloud-threedviewer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
    volumes:
      - nextcloud-main:/var/www/html
      - ./:/var/www/html/custom_apps/threedviewer:rw

volumes:
  db-data:
  nextcloud-main:
